const { Router } = require('express');
const authController = require('../controllers/authController');
const router = Router();
router.get('/signup', authController.signup_get);
router.post('/signup', authController.signup_post);
router.get('/login', authController.login_get);
router.post('/login', authController.login_post);
router.put('/profile', authController.profile_put);
router.get('/logout', authController.logout_get);
router.post("/task", authController.task_post);
module.exports = router;